require("dotenv").config();

const mongoose = require("mongoose");
const Restaurant = require("./models/Restaurant");
const Food = require("./models/Food");

const cuisineOptions = [
  "Indian",
  "Chinese",
  "Italian",
  "Mexican",
  "American",
  "Japanese",
  "Mediterranean",
  "Thai",
  "Continental",
  "Korean",
];

const cityList = [
  "Delhi",
  "Mumbai",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Pune",
  "Kolkata",
  "Jaipur",
  "Ahmedabad",
  "Lucknow",
];

const prefixList = [
  "Sunset",
  "Green",
  "Spice",
  "Urban",
  "Royal",
  "Curry",
  "Bloom",
  "Dune",
  "Fire",
  "Harvest",
  "Saffron",
  "Metro",
  "Golden",
  "Noodle",
  "Bamboo",
  "Wildfire",
  "City",
  "Velvet",
  "Harbor",
  "Cafe",
  "Luna",
  "Midnight",
  "Pepper",
  "Drift",
  "Amber",
  "Twilight",
  "Stone",
  "Savor",
  "Cedar",
  "Orbit",
  "Flame",
  "Aroma",
  "Maple",
  "Pasta",
  "Mango",
  "Riverstone",
  "Crown",
  "Horizon",
  "Bluebird",
  "Crimson",
  "Lotus",
  "Summit",
  "Pantry",
  "Cloud",
  "Tandoori",
  "Coco",
  "Basil",
  "Cinder",
  "Mellow",
  "Oak",
  "The",
  "Fresh",
  "Gourmet",
  "Bistro",
  "Riverside",
  "North",
  "Copper",
  "Silver",
  "Mosaic",
  "Daisy",
  "Seaside",
  "Sugar",
  "Wok",
  "Navajo",
  "Lime",
  "Zen",
  "Garden",
  "Comfort",
  "Supper",
  "Pine",
  "Sunrise",
  "Fusion",
  "Merry",
  "Motive",
  "Crescent",
  "Edgewood",
  "Butter",
  "Lemon",
  "Corner",
  "Rosewood",
  "Savory",
  "Lazy",
  "Tropical",
  "Pearl",
  "Lucky",
  "Courtside",
  "Starlight",
  "Bliss",
  "Taste",
  "Cinnamon",
  "Claypot",
  "Mint",
  "Pacific",
  "Brew",
  "Pinto",
  "Maharaja",
  "Village",
  "Biryani",
  "Naan",
  "Diner",
  "Tuscan",
  "Main",
  "City",
  "Palm",
  "Roast",
  "Sizzle",
  "Eden",
  "Flavor",
  "Hearth",
  "Deli",
  "Citrus",
  "Good",
  "Oyster",
  "Berry",
  "Ember",
  "Dumpling",
  "Chef",
  "Platter",
  "Mild",
  "Boardwalk",
  "Fennel",
  "Cookhouse",
  "Smoky",
  "Ginger",
  "Bite",
  "Luna",
  "Earth",
  "Tamarind",
  "Savor",
  "Horizon",
  "Cove",
  "Rustic",
  "Avenue",
  "Clover",
  "Curio",
  "Lantern",
  "Moonlight",
  "Nori",
  "Gourmand",
  "Chow",
  "Elm",
  "Canvas",
  "Modern",
];

const suffixList = [
  "Bites",
  "Kitchen",
  "Route",
  "Crave",
  "Feast",
  "House",
  "Bowl",
  "Dine",
  "Flavor",
  "Table",
  "Avenue",
  "Munch",
  "Grills",
  "Nest",
  "Bistro",
  "Eatery",
  "Spice",
  "Plate",
  "Grill",
  "Cafe",
  "Dining",
  "Crust",
  "Pot",
  "Delight",
  "Kitchen",
  "Tandoor",
  "Stem",
  "Street",
  "Co",
  "Junction",
  "Bistro",
  "Fork",
  "Lane",
  "Mint",
  "Point",
  "Mash",
  "Cafe",
  "Kitchen",
  "Grill",
  "Bistro",
  "Crust",
  "Plate",
  "Sizzlers",
  "Pine",
  "Foods",
  "Trails",
  "Curry",
  "Bean",
  "Kitchen",
  "Morsels",
  "Olive",
  "Hub",
  "Flavor",
  "Grove",
  "Bloom",
  "Grill",
  "Dine",
  "Spoon",
  "Co",
  "Circle",
  "Corner",
  "Spoon",
  "Meals",
  "Dining",
  "Table",
  "Spice",
  "Bites",
  "Spice",
  "Wick",
  "Grill",
  "Leaf",
  "Bay",
  "Cloud",
  "Fork",
  "Zest",
  "Gourmet",
  "Cove",
  "Cart",
  "Chill",
  "Station",
  "Eatery",
  "Supper",
  "Frame",
  "Basket",
  "Vault",
  "Meals",
  "Munch",
  "Kitchen",
  "Eats",
  "Bean",
  "Mill",
  "Lime",
  "Cafe",
  "Plate",
  "Circle",
  "Nibble",
  "Bites",
  "Olive",
  "Leaf",
  "Table",
  "Circle",
  "Room",
  "Fast",
  "9",
  "Plate",
  "Grill",
  "Noodle",
  "Spoon",
  "Cafe",
  "Crumb",
  "Kitchen",
  "Bites",
  "Bowl",
  "Pouch",
  "Terrace",
  "Cove",
  "Top",
  "Terrace",
  "Dine",
  "Charisma",
  "Meal",
  "Plate",
  "Bites",
  "Pepper",
  "Meal",
  "Oven",
  "Boulevard",
  "Nook",
  "Deluxe",
  "Forks",
  "Court",
  "Thread",
  "Plate",
  "Co",
  "Course",
  "Harvest",
  "Munch",
  "Pepper",
  "Roll",
  "Street",
  "Crust",
  "Eats",
  "Grounds",
  "Fountain",
  "Pine",
  "Wharf",
  "Hay",
  "Stone",
  "Delight",
  "Spice",
  "Grub",
  "Olive",
  "Bowl",
  "Egg",
  "District",
  "Court",
  "Place",
  "Masala",
  "Nook",
  "Thread",
  "Table",
  "Hub",
  "Bites",
  "Flame",
  "Spot",
  "Coast",
  "Palm",
  "Supper",
  "Grit",
  "Bloom",
  "Kitchen",
  "Spice",
  "Room",
  "Feast",
  "Ember",
  "Table",
  "Soul",
  "Diner",
  "Basket",
  "Crumb",
  "Mingle",
  "Trail",
  "Roll",
  "Trail",
  "Aroma",
  "Kitchen",
  "Noodles",
  "Diner",
  "Bites",
  "Bistro",
  "Kitchen",
  "Terrace",
  "Room",
  "Square",
  "Pine",
  "Lunch",
  "Crown",
  "Meal",
  "Lotus",
  "Naan",
  "Galaxy",
  "Charm",
  "Table",
  "Herb",
  "Grills",
  "Crumb",
  "Pearl",
  "Lane",
  "Oat",
  "Sage",
  "Bloomfield",
  "Nook",
  "Room",
  "Eatery",
  "Canvas",
  "Mint",
  "Curry",
  "Fork",
];

const categoryTemplates = {
  Starters: [
    "Crispy Corn",
    "Garlic Breadsticks",
    "Paneer Tikka",
    "Veg Spring Rolls",
    "Stuffed Mushrooms",
    "Chili Potatoes",
    "Chicken Wings",
    "Crispy Calamari",
  ],
  MainCourse: [
    "Butter Paneer",
    "Chicken Alfredo",
    "Veg Biryani",
    "Grilled Chicken Bowl",
    "Paneer Masala",
    "Prawn Curry",
    "Mushroom Risotto",
    "Chicken Shawarma",
  ],
  Pizza: [
    "Margherita Pizza",
    "Paneer Supreme",
    "Pepperoni Delight",
    "Veggie Burst",
    "Tandoori Chicken Pizza",
    "Four Cheese",
    "Loaded Veg Pizza",
    "BBQ Chicken Pizza",
  ],
  Burgers: [
    "Classic Veg Burger",
    "Crispy Chicken Burger",
    "Smash Burger",
    "Paneer Burger",
    "Double Cheese Burger",
    "BBQ Burger",
    "Crispy Fish Burger",
    "Mushroom Burger",
  ],
  Rice: [
    "Jeera Rice",
    "Fried Rice",
    "Veg Pulao",
    "Chicken Biryani",
    "Hakka Noodles",
    "Schezwan Rice",
    "Teriyaki Rice Bowl",
    "Coconut Rice",
  ],
  Desserts: [
    "Chocolate Brownie",
    "Gulab Jamun",
    "Tiramisu",
    "Cheesecake",
    "Molten Lava Cake",
    "Kulfi",
    "Ice Cream Sundae",
    "Fruit Tart",
  ],
  Beverages: [
    "Mango Shake",
    "Cold Coffee",
    "Lemon Mint Soda",
    "Masala Chai",
    "Fruit Mocktail",
    "Iced Tea",
    "Strawberry Milkshake",
    "Coconut Water",
  ],
  Snacks: [
    "Loaded Nachos",
    "Masala Fries",
    "Cheese Fingers",
    "Veg Momos",
    "Mini Sandwiches",
    "Crispy Wedges",
    "Peri Peri Fries",
    "Onion Rings",
  ],
};

function buildRestaurant(index) {
  const city = cityList[index % cityList.length];

  return {
    name: `${prefixList[index % prefixList.length]} ${suffixList[index % suffixList.length]}`,
    description: `Popular ${cuisineOptions[index % cuisineOptions.length]} dining experience with fresh ingredients and vibrant flavors.`,
    image: `https://images.unsplash.com/photo-${(index % 30) + 1500000000000}?auto=format&fit=crop&w=900&q=80`,
    cuisine: cuisineOptions[index % cuisineOptions.length],
    location: `${city}, India`,
    rating: Number((3.5 + ((index * 7) % 15) / 10).toFixed(1)),
    deliveryTime: 20 + (index % 35),
    deliveryFee: 20 + (index % 9) * 15,
    status: "Active",
  };
}

function buildFoods(restaurantId, restaurantIndex) {
  const foods = [];
  const categories = Object.keys(categoryTemplates);

  for (let i = 0; i < 120; i += 1) {
    const category = categories[i % categories.length];
    const nameBase = categoryTemplates[category][i % categoryTemplates[category].length];
    const suffixNumber = Math.floor(i / categories.length) + 1;

    foods.push({
      restaurant: restaurantId,
      name: `${nameBase} ${suffixNumber}`,
      description: `${category} favorite by restaurant ${restaurantIndex + 1}, made with fresh ingredients and bold flavors.`,
      image: `https://images.unsplash.com/photo-${(restaurantIndex + i + 1000000000000).toString()}?auto=format&fit=crop&w=900&q=80`,
      category,
      price: Number((79 + ((restaurantIndex + i) % 29) * 18 + (i % 10) * 4).toFixed(2)),
      isVeg: (i + restaurantIndex) % 4 !== 0,
      isAvailable: true,
    });
  }

  return foods;
}

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB connected for seeding");

    await Restaurant.deleteMany({});
    await Food.deleteMany({});

    const restaurants = Array.from({ length: 200 }, (_, index) => buildRestaurant(index));
    const insertedRestaurants = await Restaurant.insertMany(restaurants);

    const allFoods = [];
    insertedRestaurants.forEach((restaurant, index) => {
      allFoods.push(...buildFoods(restaurant._id, index));
    });

    for (let i = 0; i < allFoods.length; i += 500) {
      const chunk = allFoods.slice(i, i + 500);
      await Food.insertMany(chunk);
    }

    console.log(`Seeded ${insertedRestaurants.length} restaurants and ${allFoods.length} foods.`);
    process.exit(0);
  } catch (error) {
    console.error("Seeding failed:", error.message);
    process.exit(1);
  }
}

seedDatabase();

module.exports = { buildRestaurant, buildFoods };
